# Generated by Django 2.1.5 on 2019-01-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='editor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='editor',
            name='estado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='editor',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='editor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Editor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portadas'),
        ),
    ]
